title:             Smart Objects and Stupid People
email:             pseudogram@gmail.com
description:       >-
  A blog about trying to make smarter machines, so people need not apply.
author:            David Attlee
baseurl:           ""
url:               "https://pseudogram.github.io"

# Social Profiles
twitter_username:  attleed
github_username:   pseudogram
# facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
